RentHome/Web/RentHome.Web/Controllers/ContactUsController.cs
namespace RentHome.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using RentHome.Services.Data;
    using RentHome.Web.ViewModels.ContactUs;

    public class ContactUsController : BaseController
    {
        private readonly IContactService contactUsService;

        public ContactUsController(IContactService contactUsService)
        {
            this.contactUsService = contactUsService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Index(ContactInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            this.contactUsService.Contact(input);

            this.TempData["Contact"] = "Your message was sended successful!";

            return this.Redirect("/");
        }
    }
}

RentHome/Web/RentHome.Web/Controllers/MyPropertiesController.cs
namespace RentHome.Web.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using RentHome.Services.Data;
    using RentHome.Web.ViewModels.Properties;

    [Authorize]
    public class MyPropertiesController : BaseController
    {
        private readonly IMyPropertiesService mypropertyService;

        public MyPropertiesController(IMyPropertiesService mypropertyService)
        {
            this.mypropertyService = mypropertyService;
        }

        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var viewModel = new PropertiesListViewModel
            {
                Properties = this.mypropertyService.GetMyProperties(userId),
            };

            return this.View(viewModel);
        }
    }
}

RentHome/Web/RentHome.Web/Controllers/PropertiesController.cs
namespace RentHome.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using RentHome.Common;
    using RentHome.Data.Common.Repositories;
    using RentHome.Data.Models;
    using RentHome.Services.Data;
    using RentHome.Web.ViewModels.Properties;

    public class PropertiesController : BaseController
    {
        private readonly ICityService cityService;
        private readonly ICountryService countryService;
        private readonly IPropertyService propertyService;
        private readonly IRentalService rentalService;
        private readonly IRepository<Property> propertyRepository;
        private readonly IWebHostEnvironment environment;
        private readonly IContactService contactService;
        private readonly UserManager<ApplicationUser> userManager;

        public PropertiesController(
            ICityService cityService,
            ICountryService countryService,
            IPropertyService propertyService,
            IRentalService rentalService,
            IRepository<Property> propertyRepository,
            IWebHostEnvironment environment,
            IContactService contactService,
            UserManager<ApplicationUser> userManager)
        {
            this.cityService = cityService;
            this.countryService = countryService;
            this.propertyService = propertyService;
            this.rentalService = rentalService;
            this.propertyRepository = propertyRepository;
            this.environment = environment;
            this.contactService = contactService;
            this.userManager = userManager;
        }

        [ActionName("GetCity")]
        public async Task<IActionResult> GetCityAsync(int id)
        {
            var model = await this.cityService.AllCitiesByCountryAsync(id);

            return this.Json(new SelectList(model, "Id", "Name"));
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            var inputModel = this.propertyService.GetById(id);
            return this.View(inputModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditPropertyInputModel input)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            var ownerId = this.propertyRepository.All()
                .Where(x => x.Id == id)
                .Select(x => x.OwnerId)
                .FirstOrDefault();

            var managerId = this.propertyRepository.All()
                .Where(x => x.Id == id)
                .Select(x => x.ManagerId)
                .FirstOrDefault();

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            if (userId != ownerId && userId != managerId && !this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                return this.BadRequest();
            }

            await this.propertyService.UpdateAsync(id, input);

            this.TempData["Edit"] = "The changes were successful!";

            return this.RedirectToAction(nameof(this.Details), new { id });
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var cities = await this.cityService.AllCitiesAsync();
            var countries = await this.countryService.AllCountriesAsync();

            var model = new CreatePropertyInputModel
            {
                CityList = cities,
                CountryList = countries,
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePropertyInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.propertyService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.TempData["CreateFailed"] = "Failed to create property, allowed photo extensions are \"jpg\", \"png\", \"gif\"!";
                return this.Redirect("/");
            }

            this.TempData["Create"] = "You have successfully created a property and your property is awaiting inspection!";

            return this.Redirect("/");
        }

        public IActionResult All(int id = 1)
        {
            const int ItemsPerPage = 9;
            var viewModel = new PropertiesListViewModel
            {
                PageNumber = id,
                Properties = this.propertyService.GetAll(id, ItemsPerPage),
                PropertiesCount = this.propertyService.GetCount(),
                ItemsPerPage = ItemsPerPage,
            };
            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            var viewModel = this.propertyService.GetSingleProperty(id);
            viewModel.Requests = this.rentalService.MyPropertyRequests(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public IActionResult Details(SinglePropertyViewModel input, string id)
        {
            var result = input.Contact;

            string ownerEmail = this.propertyRepository.All()
                .Where(x => x.Id == id)
                .Select(x => x.Owner.Email)
                .FirstOrDefault();

            this.contactService.ContactWithOwner(result, ownerEmail);

            this.TempData["Contact"] = "Your message was sended successful!";

            return this.Redirect("/");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            await this.propertyService.DeleteAsync(id);

            this.TempData["Delete"] = "You have successfully deleted a property!";

            return this.Redirect("/Properties/All/1");
        }
    }
}

RentHome/Web/RentHome.Web/Controllers/SearchController.cs
namespace RentHome.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using RentHome.Services.Data;
    using RentHome.Web.ViewModels.Search;

    public class SearchController : BaseController
    {
        private readonly IPropertyService propertyService;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public SearchController(
            IPropertyService propertyService,
            ICityService cityService,
            ICountryService countryService)
        {
            this.propertyService = propertyService;
            this.cityService = cityService;
            this.countryService = countryService;
        }

        public async Task<IActionResult> Index()
        {
            var cities = await this.cityService.AllCitiesAsync();
            var countries = await this.countryService.AllCountriesAsync();

            var model = new SearchIndexViewModel
            {
                CityList = cities,
                CountryList = countries,
            };

            return this.View(model);
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var viewModel = new ListViewModel()
            {
                Properties = this.propertyService.Search(input),
            };
            return this.View(viewModel);
        }
    }
}

RentHome/Web/RentHome.Web/Views/Shared/_Layout.cshtml
@using RentHome.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark text-white border-bottom-0 box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Properties" asp-action="Create">Create Property</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="MyProperties" asp-action="Index">My Properties</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Properties" asp-action="All">All Properties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ContactUs" asp-action="Index">ContactUs</a>
                        </li>
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Administration" asp-controller="Properties" asp-action="Index">Visibility</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Administration" asp-controller="Location" asp-action="Index">Add Location</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="footer-area section-padding-100-0 bg-img gradient-background-overlay" style="background-image: url(img/bg-img/cta.jpg);">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container">
                <div class="row">

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <!-- Widget Title -->
                            <div class="widget-title">
                                <h6>About Us</h6>
                            </div>

                            <img src="https://technext.github.io/south/img/bg-img/footer.jpg" alt="">
                            <p>Wherever you go, we’re here to help!</p>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <!-- Widget Title -->
                            <div class="widget-title">
                                <h6>Hours</h6>
                            </div>
                            <!-- Office Hours -->
                            <div class="weekly-office-hours">
                                <ul>
                                    <li class="d-flex align-items-center justify-content-between"><span>Monday - Friday</span> <span>09 AM - 19 PM</span></li>
                                    <li class="d-flex align-items-center justify-content-between"><span>Saturday</span> <span>09 AM - 14 PM</span></li>
                                    <li class="d-flex align-items-center justify-content-between"><span>Sunday</span> <span>Closed</span></li>
                                </ul>
                            </div>
                            <!-- Address -->
                            <div class="address">
                                <h6><img src="https://technext.github.io/south/img/icons/envelope.png" alt=""> homerent325@gmail.com</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <div class="widget-title">
                                <h6>Useful Links</h6>
                            </div>
                            <ul class="useful-links-nav d-flex align-items-center">
                                <li><a href="#">Home</a></li>
                                <li><a asp-controller="Properties" asp-action="All">All properties</a></li>
                                <li><a asp-controller="Search" asp-action="Index">Search</a></li>
                                <li><a asp-controller="ContactUs" asp-action="index">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-xl-3">
                        <div class="footer-widget-area mb-100">
                            <div class="widget-title">
                                <h6>Featured Properties</h6>
                            </div>
                            <div class="featured-properties-slides owl-carousel">
                                <div class="single-featured-properties-slide">
                                    <a href="#"><img src="http://www.bocadolobo.com/en/inspiration-and-ideas/wp-content/uploads/2018/01/home-decor-2.jpg" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copywrite-text d-flex align-items-center justify-content-center">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved
            </p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
    <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647;"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
</body>
</html>

RentHome/Web/RentHome.Web/Views/Shared/_PropertiesCardPartial.cshtml
@model RentHome.Web.ViewModels.Properties.PropertiesInListViewModel
<!-- Single Featured Property -->
<div class="col-12 col-md-6 col-xl-4">
    <div class="single-featured-property mb-50 wow fadeInUp" data-wow-delay="100ms">
        <!-- Property Thumbnail -->
        <div class="property-thumb">
            <img src="@Model.ImageUrl" alt="">

            <div class="tag">
                <span>For Sale</span>
            </div>
            <div class="list-price">
                <p>$@Model.Price</p>
            </div>
        </div>
        <!-- Property Content -->
        <div class="property-content">
            <h5>@Model.Name</h5>
            <p class="location"><img src="https://technext.github.io/south/img/icons/location.png" alt="">@Model.Address</p>
            <p>@Model.Description</p>
            <a class="btn south-btn" asp-area="" asp-controller="Properties" asp-action="Details" asp-route-id="@Model.Id">View Details</a>
        </div>
    </div>
</div>

RentHome/Web/RentHome.Web/Views/Shared/_SectionImgPartial.cshtml
@model SectionImg
<section class="breadcumb-area bg-img call-to-action-area bg-fixed bg-overlay-black" style="background-image: url(@Model.Img);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcumb-content">
                    <h3 class="breadcumb-title">@Model.Name</h3>
                </div>
            </div>
        </div>
    </div>
</section>